# -*- coding: utf-8 -*-
import pathlib
import shutil
import keras_autodoc

PAGES = {    
    'documentation/dynamicregressor.md': [
        'ahead.DynamicRegressor.DynamicRegressor.DynamicRegressor',
        'ahead.DynamicRegressor.DynamicRegressor.DynamicRegressor.forecast'
    ],
    'documentation/eat.md': [
        'ahead.EAT.EAT.EAT',
        'ahead.EAT.EAT.EAT.forecast'
    ],
    'documentation/ridge2regressor.md': [
        'ahead.Ridge2.Ridge2Regressor.Ridge2Regressor',
        'ahead.Ridge2.Ridge2Regressor.Ridge2Regressor.forecast'
    ],
    'documentation/var.md': [
        'ahead.VAR.VAR.VAR',
        'ahead.VAR.VAR.VAR.forecast',
    ],
}

ahead_dir = pathlib.Path(__file__).resolve().parents[1]


def generate(dest_dir):
    template_dir = ahead_dir / 'docs' / 'templates'

    doc_generator = keras_autodoc.DocumentationGenerator(
        PAGES,
        'https://github.com/Techtonique/ahead',
        template_dir,
        #ahead_dir / 'examples'
    )
    doc_generator.generate(dest_dir)

    readme = (ahead_dir / 'README.md').read_text()
    index = (template_dir / 'index.md').read_text()
    index = index.replace('{{autogenerated}}', readme[readme.find('##'):])
    (dest_dir / 'index.md').write_text(index, encoding='utf-8')
    shutil.copyfile(ahead_dir / 'CONTRIBUTING.md',
                    dest_dir / 'contributing.md')
    #shutil.copyfile(ahead_dir / 'docs' / 'extra.css',
    #                dest_dir / 'extra.css')


if __name__ == '__main__':
    generate(ahead_dir / 'docs' / 'sources')