name: Publish Python 🐍 distribution 📦 to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.3.2  # or rocker/r-ver:4.3.2 or another Rocker image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools twine rpy2

      - name: Install R ahead package
        run: |
          Rscript -e "options(repos = c(techtonique = 'https://r-packages.techtonique.net', CRAN = 'https://cloud.r-project.org')); utils::install.packages('ahead', dependencies=TRUE)"

      - name: Build distribution
        run: python setup.py sdist bdist_wheel

      - name: Run examples 
        run: pip install . && find examples -maxdepth 2 -name "*.py" -exec  python3 {} \;

      - name: Publish to PyPI                
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_AHEAD }}
          repository-url: https://upload.pypi.org/legacy/
